import { useState } from "react";
import { format, addDays } from "date-fns";
import { CheckCircle2, Calendar as CalendarIcon, Video, UserRound, Clock, AlertCircle } from "lucide-react";
import { useAppStore } from "@/store/use-app-store";
import { Button } from "@/components/ui/Button";
import { Badge } from "@/components/ui/Badge";
import { cn } from "@/lib/utils";

export function SchedulingTab() {
  const { triageData, setActiveTab, markTabComplete, addLog, patientInfo } = useAppStore();
  const [selectedDate, setSelectedDate] = useState<Date>(addDays(new Date(), 1));
  const [selectedTime, setSelectedTime] = useState<string>("10:00 AM");
  const [isBooked, setIsBooked] = useState(false);
  const [appointmentId, setAppointmentId] = useState("");

  if (!triageData) return null;

  const { schedulingInfo, emergencyAnalysis } = triageData;

  // Block scheduling if emergency
  if (emergencyAnalysis.is_emergency && !emergencyAnalysis.can_proceed_to_scheduling) {
    return (
      <div className="flex flex-col items-center justify-center h-full text-center space-y-4">
        <AlertCircle className="w-16 h-16 text-destructive" />
        <h3 className="text-2xl text-white font-display">Scheduling Blocked</h3>
        <p className="text-muted-foreground max-w-md">
          Due to the critical nature of your symptoms, online scheduling has been disabled. Please seek immediate emergency medical care.
        </p>
      </div>
    );
  }

  const handleConfirm = () => {
    const id = `APT-${Math.random().toString(36).substring(2, 8).toUpperCase()}`;
    setAppointmentId(id);
    setIsBooked(true);
    addLog('SCHEDULING_AGENT', 'Appointment confirmed', `Booking ID: ${id} for ${format(selectedDate, 'MMM d')} at ${selectedTime}.`);
    markTabComplete('scheduling');
  };

  const handleDone = () => {
    setActiveTab('followup');
    addLog('FOLLOWUP_AGENT', 'Tracker initialized', 'Awaiting post-visit check-in.');
  };

  if (isBooked) {
    return (
      <div className="max-w-xl mx-auto w-full animate-in zoom-in-95 duration-500">
        <div className="glass-card rounded-2xl p-8 text-center relative overflow-hidden">
          <div className="absolute top-0 left-0 w-full h-1 bg-success" />
          <div className="w-20 h-20 bg-success/20 rounded-full flex items-center justify-center mx-auto mb-6">
            <CheckCircle2 className="w-10 h-10 text-success" />
          </div>
          <h2 className="text-3xl font-display text-white mb-2">Booking Confirmed</h2>
          <p className="text-muted-foreground mb-8">Your appointment has been successfully scheduled.</p>
          
          <div className="bg-white/5 border border-white/10 rounded-xl p-6 text-left space-y-4 mb-8">
            <div className="flex justify-between items-center border-b border-white/5 pb-4">
              <span className="text-sm text-muted-foreground">Booking ID</span>
              <span className="font-mono text-white font-bold">{appointmentId}</span>
            </div>
            <div className="flex justify-between items-center border-b border-white/5 pb-4">
              <span className="text-sm text-muted-foreground">Patient</span>
              <span className="text-white font-medium">{patientInfo?.name}</span>
            </div>
            <div className="flex justify-between items-center border-b border-white/5 pb-4">
              <span className="text-sm text-muted-foreground">Date & Time</span>
              <span className="text-white font-medium">{format(selectedDate, 'MMMM d, yyyy')} • {selectedTime}</span>
            </div>
            <div className="flex justify-between items-center">
              <span className="text-sm text-muted-foreground">Type</span>
              <Badge variant="outline" className="text-white border-white/20">
                {schedulingInfo.appointment_type_recommendation}
              </Badge>
            </div>
          </div>

          <Button size="lg" className="w-full" onClick={handleDone}>
            Proceed to Follow-up Tracker
          </Button>
        </div>
      </div>
    );
  }

  // Mock available times
  const timeSlots = ["09:00 AM", "10:00 AM", "11:30 AM", "02:00 PM", "04:15 PM", "05:30 PM"];

  return (
    <div className="max-w-5xl mx-auto w-full animate-in fade-in slide-in-from-bottom-4 duration-500 pb-10">
      
      <div className="mb-8">
        <h2 className="text-3xl font-display text-white mb-2">Finalize Appointment</h2>
        <p className="text-muted-foreground">Select a time slot and review pre-visit instructions generated by the AI.</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        
        {/* Left Col: Scheduling Form */}
        <div className="space-y-6">
          <div className="glass-card rounded-2xl p-6">
            <div className="flex items-center justify-between mb-6">
              <h3 className="font-bold text-white flex items-center gap-2">
                <CalendarIcon className="w-5 h-5 text-primary" /> Date & Time
              </h3>
              <Badge variant="secondary" className="font-mono">{schedulingInfo.estimated_duration} Slot</Badge>
            </div>
            
            {/* Simple mock calendar selection */}
            <div className="grid grid-cols-3 gap-2 mb-6">
              {[0, 1, 2].map(offset => {
                const date = addDays(new Date(), offset + 1);
                const isSelected = format(date, 'yyyy-MM-dd') === format(selectedDate, 'yyyy-MM-dd');
                return (
                  <button
                    key={offset}
                    onClick={() => setSelectedDate(date)}
                    className={cn(
                      "p-3 rounded-xl border flex flex-col items-center justify-center transition-all",
                      isSelected ? "bg-primary/20 border-primary text-primary" : "bg-white/5 border-white/10 text-muted-foreground hover:bg-white/10"
                    )}
                  >
                    <span className="text-xs uppercase font-bold mb-1">{format(date, 'EEE')}</span>
                    <span className="text-xl font-bold">{format(date, 'd')}</span>
                  </button>
                );
              })}
            </div>

            <div className="space-y-3">
              <h4 className="text-xs font-bold uppercase tracking-wider text-muted-foreground">Available Slots</h4>
              <div className="grid grid-cols-3 gap-2">
                {timeSlots.map(time => (
                  <button
                    key={time}
                    onClick={() => setSelectedTime(time)}
                    className={cn(
                      "py-2 rounded-lg text-sm border font-medium transition-all",
                      selectedTime === time ? "bg-primary text-primary-foreground border-primary shadow-[0_0_15px_rgba(13,148,136,0.3)]" : "bg-white/5 border-white/10 text-white/80 hover:bg-white/10"
                    )}
                  >
                    {time}
                  </button>
                ))}
              </div>
            </div>
          </div>

          <div className="glass-card rounded-2xl p-6">
            <h3 className="font-bold text-white mb-4">Consultation Type</h3>
            <div className="grid grid-cols-2 gap-4">
              <button className={cn(
                "p-4 rounded-xl border flex flex-col items-center gap-3 transition-all",
                schedulingInfo.appointment_type_recommendation === "In-Person" ? "bg-primary/10 border-primary text-primary" : "bg-white/5 border-white/10 text-muted-foreground"
              )}>
                <UserRound className="w-6 h-6" />
                <span className="font-semibold text-sm">In-Person</span>
                {schedulingInfo.appointment_type_recommendation === "In-Person" && <Badge className="absolute top-2 right-2 text-[8px] px-1 py-0 h-4">Recommended</Badge>}
              </button>
              <button className={cn(
                "p-4 rounded-xl border flex flex-col items-center gap-3 transition-all relative",
                schedulingInfo.appointment_type_recommendation === "Telehealth" ? "bg-primary/10 border-primary text-primary" : "bg-white/5 border-white/10 text-muted-foreground"
              )}>
                <Video className="w-6 h-6" />
                <span className="font-semibold text-sm">Telehealth</span>
                {schedulingInfo.appointment_type_recommendation === "Telehealth" && <Badge className="absolute top-2 right-2 text-[8px] px-1 py-0 h-4">Recommended</Badge>}
              </button>
            </div>
          </div>
        </div>

        {/* Right Col: AI Prep Instructions */}
        <div className="space-y-6">
          <div className="glass-card rounded-2xl p-6 border-t-4 border-t-blue-500">
             <h3 className="font-bold text-white mb-4">AI Pre-Visit Checklist</h3>
             
             {schedulingInfo.fasting_required && (
               <div className="mb-6 p-4 rounded-xl bg-amber-500/10 border border-amber-500/20 flex gap-3 items-start">
                 <AlertTriangle className="w-5 h-5 text-amber-500 shrink-0" />
                 <div>
                   <h4 className="text-sm font-bold text-amber-500">Fasting Required</h4>
                   <p className="text-xs text-amber-500/80 mt-1">{schedulingInfo.fasting_instructions}</p>
                 </div>
               </div>
             )}

             <div className="space-y-6">
               <div>
                 <h4 className="text-xs font-bold uppercase text-muted-foreground mb-3">What to bring</h4>
                 <ul className="space-y-2">
                   {schedulingInfo.what_to_bring.map((item, i) => (
                     <li key={i} className="text-sm text-white/90 flex items-center gap-2">
                       <CheckCircle2 className="w-4 h-4 text-blue-400 shrink-0" />
                       {item}
                     </li>
                   ))}
                 </ul>
               </div>

               <div>
                 <h4 className="text-xs font-bold uppercase text-muted-foreground mb-3">Questions to ask doctor</h4>
                 <ul className="space-y-2">
                   {schedulingInfo.questions_to_ask_doctor.map((q, i) => (
                     <li key={i} className="text-sm text-white/90 p-3 rounded-lg bg-white/5 border border-white/10">
                       "{q}"
                     </li>
                   ))}
                 </ul>
               </div>
             </div>
          </div>

          <div className="pt-4">
             <Button size="lg" className="w-full h-14 text-lg shadow-primary/30 shadow-lg" onClick={handleConfirm}>
               Confirm Booking
             </Button>
             <p className="text-center text-xs text-muted-foreground mt-4">
               By confirming, you agree to the clinic's cancellation policy.
             </p>
          </div>
        </div>

      </div>
    </div>
  );
}
